### PR TITLE
HotFix build date parsing

### LINKED ISSUE #247: Binary released as part of v2.11.4 can not parse the build date
Reported in Slack on recent [v2.11.4](https://github.com/bblfsh/bblfshd/releases/tag/v2.11.4).

When running on linux, a release tarball contains a binary that can not be started.

Steps to reproduce:

```
cat /etc/issue
 Debian GNU/Linux 9 \n \l
wget https://github.com/bblfsh/bblfshd/releases/download/v2.11.4/bblfshd_v2.11.4_linux_amd64.tar.gz
tar xvzf bblfshd_v2.11.4_linux_amd64.tar.gz
sudo apt-get install libostree-dev

sudo ./bblfshd_linux_amd64/bblfshd
 [2019-02-07T11:54:34+01:00]  INFO bblfshd version: v2.11.4 (build: "2019-02-05T19:16:31+0000")
 [2019-02-07T11:54:34+01:00]  INFO initializing runtime at /var/lib/bblfshd
 [2019-02-07T11:54:34+01:00] ERROR wrong date format for build: parsing time ""2019-02-05T19:16:31+0000"" as "2006-01-02T15:04:05-0700": cannot parse ""2019-02-05T19
:16:31+0000"" as "2006"
```

The reason seems to be extra `"` in the build time.

Plan 

 - [x] reproduce on local linux build
 - [x] try reverting https://github.com/bblfsh/bblfshd/pull/242/
 - [x] try `strings.Trim(build , ""\")`
 - [x] restore `go build ./cmd/bblfshd` behavior from #233, by making server similar to defaults for the [drivers](https://github.com/bblfsh/bblfshd/blob/49f427820b544393c2891c5d9455f529f784c260/daemon/service.go#L313) in case the date was not provided.

TEST PLAN: 
   - container works
    `make build && docker run -d --name bblfshd-bug --privileged -p 9432:9432 bblfsh/bblfshd:dev-2e8884b-dirty`
   - `bblfshd` binary works
    `make packages && ./build/bblfshd_linux_amd64/bblfshd` 
   - dev build of `bblfshd` bianry works
    `go build ./cmd/bblfshd && ./bblfshd`

### PR DESCRIPTION
**Pull request by bzz**
Fixes #247 (please read it for more context)

Consists of (see individual commits)
 - reverting #242 
 - small refactoring to unify date parsing
 - sync quotation \w `src-d/ci` as a standard
 - restoring `go build` workflow after #233

### CODE REVIEW

**Comment by bzz** [comment]
Tested, both Docker and local build on linux work as expected

File: daemon/daemon.go [hunk 1]
```diff
@@ -19,6 +19,8 @@ import (
 	protocol2 "gopkg.in/bblfsh/sdk.v2/protocol"
 )
 
+const BuildDateFormat = "2006-01-02T15:04:05-0700"
```
Comment (dennwc) [inline daemon/daemon.go]: This is not really related to the daemon package. It's only the `bblfshd/main.go` who parses it that way.

File: cmd/bblfshd/main.go [hunk 2]
```diff
@@ -115,10 +117,15 @@ func main() {
...
 	}
 
-	parsedBuild, err := time.Parse("2006-01-02T15:04:05-0700", build)
+	parsedBuild, err := time.Parse(daemon.BuildDateFormat, build)
 	if err != nil {
-		logrus.Errorf("wrong date format for build: %s", err)
-		os.Exit(1)
+		logrus.Errorf("wrong date format for this build: %s", err)
+		if build == defaultBuild {
+			build = time.Now().Format(daemon.BuildDateFormat)
```
Comment (dennwc) [inline cmd/bblfshd/main.go]: Why not leave it as `undefined`, but skip an error?

File: cmd/bblfshd/main.go [hunk 3]
```diff
@@ -115,10 +117,15 @@ func main() {
 		os.Exit(1)
 	}
 
-	parsedBuild, err := time.Parse("2006-01-02T15:04:05-0700", build)
+	parsedBuild, err := time.Parse(daemon.BuildDateFormat, build)
 	if err != nil {
-		logrus.Errorf("wrong date format for build: %s", err)
-		os.Exit(1)
+		logrus.Errorf("wrong date format for this build: %s", err)
```
Comment (dennwc) [inline cmd/bblfshd/main.go]: This error should be in `else` for `undefined`.

File: cmd/bblfshd/main.go (hunk 2 above)
Comment (bzz) [reply cmd/bblfshd/main.go]: because interface of the NewDaemon has changed and it requires parsed `time.Time` no?

File: daemon/daemon.go (hunk 1 above)
Comment (bzz) [reply daemon/daemon.go]: It's just retrofitting existing existing code structure to minimize the changes - if you look below, this is used in `daemon_test.go`, thus the location.

File: cmd/bblfshd/main.go (hunk 3 above)
Comment (bzz) [reply cmd/bblfshd/main.go]: I like the idea of this being logged in any case, but can move to the `os.Exit()` branch, if that is what you are asking for.

Comment (dennwc) [reply cmd/bblfshd/main.go]: Yes, I think exit is better. Running dev version shouldn't lead to errors like this :)

File: cmd/bblfshd/main.go (hunk 2 above)
Comment (dennwc) [reply cmd/bblfshd/main.go]: Sure, but you still pass parsed time (zero `time.Time`) to `NewDaemon` in this case. It doesn't matter what `build` is.

File: daemon/daemon.go (hunk 1 above)
Comment (dennwc) [reply daemon/daemon.go]: But the test is free to use any format. `NewDaemon` doesn't enforce any specific format.

Comment (bzz) [reply daemon/daemon.go]: sure, but usually it's kind of good idea to test with the format that is going to be used in prod, no?

File: cmd/bblfshd/main.go (hunk 2 above)
Comment (bzz) [reply cmd/bblfshd/main.go]: Oh, that is a bug, thank you for catching!

Comment (bzz) [reply cmd/bblfshd/main.go]: addressed in parsedBuild

File: daemon/daemon.go (hunk 1 above)
Comment (dennwc) [reply daemon/daemon.go]: The point is that we should either move the constant to this package and dictate the format there (that is not a good idea I think) or somehow write the test for the binary itself (`package main`).

Comment (bzz) [reply daemon/daemon.go]: Got it! Decouple date format parsing and daemon package tests in d4ea40b

**Comment by bzz** [comment]
All feedback addressed, ready for another round @dennwc

**Comment by bzz** [comment]
Merging&releasing a new version as soon as CI is green.
